# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /mnt/e/bioconda-recipes/recipes/gto
# ------------------------------------------------

package:
    name: gto2
    version: '0.2.0'

source:
    git_rev: v0.2.0
    git_url: https://github.com/cobilab/gto2.git

requirements:
    build:
        - gxx_linux-64
        - cmake

about:
    home: https://cobilab.github.io/gto2/
    license: GPL v3 License
    license_family: GPL
    summary: The second version of the genomics-proteomics toolkit
